services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: category
      MYSQL_PASSWORD: 1234
      MYSQL_USER: admin
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql:/var/lib/mysql