server:
  port: 9090

spring:
  application:
    name: category-admin
  docker:
    compose:
      enabled: off

spring.config.import:
  - optional:classpath:application-data-jpa.yml
  - optional:classpath:application-data-redis.yml

debug: true
