spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

---
spring.config.activate.on-profile: local
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/category
    username: admin
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never

---
spring.config.activate.on-profile: prod

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/category
    username: admin
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
